[build]
  # Build command
  command = "npm ci && npm run build"
  
  # Publish directory (where the built files are)
  publish = "dist"

[build.environment]
  # Node version
  NODE_VERSION = "18"
  
  # Don't set NODE_ENV to production during build to allow devDependencies
  NPM_FLAGS = "--production=false"

# Redirect all requests to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://finpilot-api.onrender.com;"